[directory]
truncation_length = 6
truncate_to_repo = false

[git_branch]
style = "bold green"
symbol = " "

[git_status]
# ahead = "↑ ${count}"
# behind = "↓ ${count}"
# diverged = "${ahead_count}↕${behind_count}"
# conflicted = "! ${count}"
# untracked = "? ${count}"
# stashed = "$ ${count}"
# modified = "~ ${count}"
# staged = "+ ${count}"
# renamed = "> ${count}"
# deleted = "- ${count}"

[golang]
symbol = " "

[rust]
symbol = " "

[python]
symbol = "  "
format = 'with [${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
