command_timeout = 10000000
add_newline = false  # remove extra height padding

[aws]
symbol = "  "

[buf]
symbol = " "

[c]
symbol = " "

[directory]
truncate_to_repo = false
truncation_length = 5
read_only = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
style = "bold green"
symbol = " "

[golang]
symbol = " "

[java]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[package]
disabled = true
symbol = " "

[python]
symbol = " "

[rlang]
symbol = "ﳒ "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "
